version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocritic
    - revive

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - revive

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: indent-error-flow
        - name: blank-imports
        - name: context-as-argument
        - name: error-return

    gocritic:
      enabled-checks:
        - rangeValCopy
