version: 2

builds:
  - main: .
    binary: saws
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: tarball
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: lvstb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    ids:
      - tarball
    name: saws
    homepage: "https://github.com/lvstb/saws"
    description: "AWS SSO credentials, without the pain"
    license: "MIT"
    install: |
      bin.install "saws"
    test: |
      system "#{bin}/saws", "--version"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
